"""
Parallel / Map-Reduce Agentic Pattern — LangGraph Implementation
================================================================

This script implements the Parallel / Map-Reduce pattern where:
1. A Planner node dynamically decomposes a complex query into independent tasks.
2. A Conditional Edge maps these tasks to parallel worker nodes using the Send API.
3. Multiple Worker nodes execute simultaneously to perform research via Tavily Search.
4. An Aggregator node reduces the parallel findings, sorts them, and synthesizes the final report.

Architecture:
                       ┌──> Worker [0] ──┐
    START ─> Planner ──┼──> Worker [1] ──┼─> Reducer (List Add) ─> Aggregator ─> END
                       └──> Worker [N] ──┘

Key Concepts:
- Dynamic parallel scaling using LangGraph's Send API.
- Thread-safe state accumulation via Pydantic model reducers (operator.add).
- Deterministic reduction by sorting asynchronous results by index.
"""

# ==============================================================================
# Step 1: Imports and Setup
# ==============================================================================

import operator
import os
from typing import Annotated, Any, Dict, List, TypedDict

from dotenv import load_dotenv
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.constants import Send
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

load_dotenv()

# Strong model for planning and synthesis
planner_model = ChatOpenAI(model="gpt-4o", temperature=0)

# Lighter, faster model for parallel worker nodes
executor_model = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# Initialize Search Tool
search_tool = TavilySearchResults(max_results=3)


# ==============================================================================
# Step 2: Define Structured Output Schemas and State
# ==============================================================================

class TaskDescription(BaseModel):
    """Description of a single, independent sub-task."""
    task: str = Field(
        description="A specific, focused research query (e.g., 'SpaceX Starship development updates')."
    )
    description: str = Field(
        description="Brief context outlining what key questions need to be answered."
    )


class Plan(BaseModel):
    """Output of the planner — a collection of independent sub-tasks."""
    tasks: List[TaskDescription] = Field(
        description="A list of 3-4 completely independent tasks that can be researched concurrently."
    )


class WorkerResult(BaseModel):
    """Output generated by a single worker node."""
    task: str = Field(description="The task that was executed.")
    index: int = Field(description="The original index of the task (used for sorting).")
    findings: str = Field(description="The summarized findings from the research.")


class MapReduceState(TypedDict):
    """
    State that flows through the Map-Reduce workflow.
    
    Fields:
        input: The initial complex query/topic.
        tasks: The list of tasks generated by the planner.
        results: Accumulated list of findings from the workers (uses reducer).
        final_response: The final compiled, structured markdown report.
    """
    input: str
    tasks: List[TaskDescription]
    results: Annotated[List[WorkerResult], operator.add]
    final_response: str


class WorkerState(TypedDict):
    """
    The isolated state slice passed to each parallel worker instance.
    """
    task: str
    index: int
    description: str


# ==============================================================================
# Step 3: Define the Planner Node
# ==============================================================================

planner_with_structure = planner_model.with_structured_output(Plan)

def planner_node(state: MapReduceState) -> dict:
    """
    Analyzes the user's objective and decomposes it into independent sub-tasks.
    
    This node runs once. It splits a complex topic into discrete tasks that 
    can be researched concurrently without dependencies on each other.
    """
    objective = state["input"]
    
    prompt = f"""You are a master planning assistant. Your job is to break down a complex,
multi-faceted research topic into 3-4 completely independent sub-tasks.

Rules:
- The tasks MUST be independent (no task should depend on the result of another).
- Each task should focus on a specific sub-topic or entity.
- Design the tasks so they can be run in parallel.
- Include a descriptive context detailing what the research should look for.

Topic to analyze: {objective}

Generate the plan now:"""

    plan = planner_with_structure.invoke(prompt)
    
    print(f"\n{'='*60}")
    print(f"📋 PLAN GENERATED — {len(plan.tasks)} Parallel Tasks:")
    print(f"{'='*60}")
    for i, t in enumerate(plan.tasks, 1):
        print(f"   {i}. Task: {t.task}")
        print(f"      Context: {t.description}")
    print()
    
    return {"tasks": plan.tasks, "results": []}


# ==============================================================================
# Step 4: Define the Map Edge (Dynamic Routing)
# ==============================================================================

def map_to_workers(state: MapReduceState) -> List[Send]:
    """
    Conditional edge that creates multiple Send objects.
    
    Each Send object represents a parallel worker instance. It targets the 
    'worker_node' and passes it a custom sliced WorkerState.
    """
    tasks = state["tasks"]
    print(f"[Mapper] Dispatching {len(tasks)} parallel workers concurrently...")
    
    sends = []
    for i, t in enumerate(tasks):
        worker_state = {
            "task": t.task,
            "index": i,
            "description": t.description
        }
        sends.append(Send("worker_node", worker_state))
        
    return sends


# ==============================================================================
# Step 5: Define the Worker Node
# ==============================================================================

def worker_node(state: WorkerState) -> dict:
    """
    Executes research for a single sub-task concurrently.
    
    Uses Tavily Search to gather real-time data and GPT-4o-mini to summarize
    findings. The result is appended to the overall state list via the reducer.
    """
    task = state["task"]
    index = state["index"]
    description = state["description"]
    
    print(f"⚙️  [Worker {index}] Researching: '{task}'...")
    
    # 1. Execute Tavily Search
    search_query = f"{task} {description}"
    search_results = search_tool.invoke(search_query)
    
    # 2. Format search context
    context_str = ""
    for idx, r in enumerate(search_results, 1):
        context_str += f"[{idx}] Source: {r.get('url')}\nContent: {r.get('content')}\n\n"
        
    # 3. Prompt executor to synthesize search results
    prompt = f"""You are a research analyst. You are researching the following task:

Task: {task}
Context: {description}

Search Results:
{context_str}

Analyze the search results above and write a detailed summary of your findings. 
Be factual, structured, and cite sources if relevant. Keep it to 1-2 paragraphs of key points."""

    response = executor_model.invoke([HumanMessage(content=prompt)])
    
    # 4. Wrap result in a WorkerResult object
    result_obj = WorkerResult(
        task=task,
        index=index,
        findings=response.content
    )
    
    print(f"✅ [Worker {index}] Completed: '{task}'")
    
    # Return result to be appended via operator.add reducer
    return {"results": [result_obj]}


# ==============================================================================
# Step 6: Define the Aggregator Node (Reduce Phase)
# ==============================================================================

def aggregator_node(state: MapReduceState) -> dict:
    """
    Aggregates and compiles all parallel research results.
    
    First, it sorts the asynchronous outputs by their original index to 
    maintain the planner's intended structure. Then, it uses GPT-4o to 
    synthesize a cohesive, high-quality final markdown report.
    """
    print(f"\n{'='*60}")
    print("[Aggregator] All workers complete. Synthesizing final report...")
    print(f"{'='*60}")
    
    results_list: List[WorkerResult] = state["results"]
    
    # Sort results by the original index to ensure deterministic output ordering
    sorted_results = sorted(results_list, key=lambda x: x.index)
    
    # Format the gathered research sections
    research_summary = ""
    for r in sorted_results:
        research_summary += f"## Research Task {r.index + 1}: {r.task}\n"
        research_summary += f"{r.findings}\n\n"
        
    # Ask the planner model to write a final, comprehensive executive report
    prompt = f"""You are an expert technical writer. You have been given research findings
gathered by several parallel research agents.

Original Objective: {state['input']}

Research Findings:
{research_summary}

Your task is to write a cohesive, comprehensive, and beautiful executive report 
based on these findings. 
- Create a compelling title.
- Start with a solid Executive Summary.
- Organize the findings into logical sections with markdown headers.
- Write in a highly professional tone.
- Do not add placeholders or hallucinate new facts not in the research findings.
"""

    response = planner_model.invoke([HumanMessage(content=prompt)])
    
    return {"final_response": response.content}


# ==============================================================================
# Step 7: Build and Compile the Graph
# ==============================================================================

builder = StateGraph(MapReduceState)

# Add Nodes
builder.add_node("planner", planner_node)
builder.add_node("worker_node", worker_node)
builder.add_node("aggregator", aggregator_node)

# Add Edges
builder.add_edge(START, "planner")

# Map Phase: planner calls map_to_workers, which fires multiple worker_node instances via Send API
builder.add_conditional_edges("planner", map_to_workers, ["worker_node"])

# Reduce Phase: Once all worker_node instances finish, execution flows to aggregator
builder.add_edge("worker_node", "aggregator")
builder.add_edge("aggregator", END)

# Compile
workflow = builder.compile()


# ==============================================================================
# Step 8: Run the Graph
# ==============================================================================

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("🚀 PARALLEL / MAP-REDUCE RESEARCH PIPELINE — Starting")
    print("=" * 60)
    
    # Query requiring research on multiple distinct entities
    query = (
        "Analyze and compare the major updates and milestone achievements in 2026 "
        "for SpaceX Starship, NASA Artemis Program, and ESA Ariane 6."
    )
    
    result = workflow.invoke({
        "input": query,
        "tasks": [],
        "results": [],
        "final_response": ""
    })
    
    # Print the final report
    print("\n" + "=" * 80)
    print("🎯 FINAL EXECUTIVE REPORT")
    print("=" * 80)
    print(result["final_response"])
    print("=" * 80)
